#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D365.Plugins.Entities
{
	
	
	/// <summary>
	/// Shows the different options for online meetings.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum onlinemeetingtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TeamsMeeting = 1,
	}
}
#pragma warning restore CS1591
